/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_X0m4SNAUt",
  aws_user_pools_web_client_id: "73uvei46iskanm62cp5mfov4ks",
  oauth: {},
  aws_appsync_graphqlEndpoint:
    "https://cbmngegavnfathdz73252py46q.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-5wfjagexmnbzrbv66ifeil746e",
};

export default awsmobile;
